// Course suggestions data
const COURSE_SUGGESTIONS = [
    {name:"Financial Accounting",code:"ACC 201",level:"Sophomore",college:"College of Business",department:"Accounting",subdiscipline:""},
    {name:"Managerial Accounting",code:"ACC 202",level:"Sophomore",college:"College of Business",department:"Accounting",subdiscipline:""},
    {name:"Introduction to Art History",code:"AHI 101",level:"Freshman",college:"College of the Arts",department:"Art History",subdiscipline:""},
    {name:"Art History I: Ancient to Medieval",code:"AHI 110",level:"Freshman",college:"College of the Arts",department:"Art History",subdiscipline:""},
    {name:"Art History II: Renaissance to Modern",code:"AHI 111",level:"Freshman",college:"College of the Arts",department:"Art History",subdiscipline:""},
    {name:"Methods of Visual Analysis",code:"AHI 210",level:"Sophomore",college:"College of the Arts",department:"Art History",subdiscipline:""},
    {name:"Global Art Histories",code:"AHI 220",level:"Sophomore",college:"College of the Arts",department:"Art History",subdiscipline:""},
    {name:"History of Architecture & the Built Environment",code:"AHI 230",level:"Sophomore",college:"College of the Arts",department:"Art History",subdiscipline:""},
    {name:"Digital Curating & Museum Studies",code:"AHI 240",level:"Sophomore",college:"College of the Arts",department:"Art History",subdiscipline:""},
    {name:"Applied AI Foundations",code:"AIT 201",level:"Sophomore",college:"College of Computing",department:"Artificial Intelligence",subdiscipline:""},
    {name:"Introduction to Anthropology",code:"ANT 101",level:"Freshman",college:"College of Social Sciences",department:"Anthropology",subdiscipline:""},
    {name:"Cultural Anthropology",code:"ANT 210",level:"Sophomore",college:"College of Social Sciences",department:"Anthropology",subdiscipline:""},
    {name:"Archaeology",code:"ANT 220",level:"Sophomore",college:"College of Social Sciences",department:"Anthropology",subdiscipline:""},
    {name:"Biological Anthropology",code:"ANT 230",level:"Sophomore",college:"College of Social Sciences",department:"Anthropology",subdiscipline:""},
    {name:"Language & Culture",code:"ANT 240",level:"Sophomore",college:"College of Social Sciences",department:"Anthropology",subdiscipline:""},
    {name:"Intro Business Analytics",code:"BAN 201",level:"Sophomore",college:"College of Business",department:"Business Analytics",subdiscipline:""},
    {name:"Business Statistics & Modeling",code:"BAN 210",level:"Sophomore",college:"College of Business",department:"Business Analytics",subdiscipline:""},
    {name:"Spreadsheet Modeling",code:"BAN 220",level:"Sophomore",college:"College of Business",department:"Business Analytics",subdiscipline:""},
    {name:"SQL for Analytics",code:"BAN 230",level:"Sophomore",college:"College of Business",department:"Business Analytics",subdiscipline:""},
    {name:"Data Visualization",code:"BAN 240",level:"Sophomore",college:"College of Business",department:"Business Analytics",subdiscipline:""},
    {name:"Foundations of Biology with Lab",code:"BIO 101",level:"Freshman",college:"College of Science",department:"Biology",subdiscipline:""},
    {name:"Cell & Molecular Biology with Lab",code:"BIO 102",level:"Freshman",college:"College of Science",department:"Biology",subdiscipline:""},
    {name:"Genetics with Lab",code:"BIO 201",level:"Sophomore",college:"College of Science",department:"Biology",subdiscipline:""},
    {name:"Ecology & Evolution with Lab",code:"BIO 202",level:"Sophomore",college:"College of Science",department:"Biology",subdiscipline:""},
    {name:"Cell Biology",code:"BIO 210",level:"Sophomore",college:"College of Science",department:"Biology",subdiscipline:""},
    {name:"Geomatics & Digital Terrain Analysis with Lab",code:"CEE 210",level:"Sophomore",college:"College of Engineering",department:"Civil & Environmental Engineering",subdiscipline:""},
    {name:"Structural Analysis",code:"CEE 220",level:"Sophomore",college:"College of Engineering",department:"Civil & Environmental Engineering",subdiscipline:""},
    {name:"Geotechnical Engineering with Lab",code:"CEE 240",level:"Sophomore",college:"College of Engineering",department:"Civil & Environmental Engineering",subdiscipline:""},
    {name:"Environmental Engineering with Lab",code:"CEE 250",level:"Sophomore",college:"College of Engineering",department:"Civil & Environmental Engineering",subdiscipline:""},
    {name:"Transportation Engineering",code:"CEE 260",level:"Sophomore",college:"College of Engineering",department:"Civil & Environmental Engineering",subdiscipline:""},
    {name:"General Chemistry I with Lab",code:"CHE 101",level:"Freshman",college:"College of Science",department:"Chemistry",subdiscipline:""},
    {name:"General Chemistry II with Lab",code:"CHE 102",level:"Freshman",college:"College of Science",department:"Chemistry",subdiscipline:""},
    {name:"Organic Chemistry I with Lab",code:"CHE 201",level:"Sophomore",college:"College of Science",department:"Chemistry",subdiscipline:""},
    {name:"Organic Chemistry II with Lab",code:"CHE 202",level:"Sophomore",college:"College of Science",department:"Chemistry",subdiscipline:""},
    {name:"Introduction to Communication",code:"COM 101",level:"Freshman",college:"College of Humanities",department:"Communication",subdiscipline:""},
    {name:"Public Speaking / Professional Communication",code:"COM 110",level:"Freshman",college:"College of Humanities",department:"Communication",subdiscipline:""},
    {name:"Media & Society",code:"COM 210",level:"Sophomore",college:"College of Humanities",department:"Communication",subdiscipline:""},
    {name:"Communication Theory",code:"COM 220",level:"Sophomore",college:"College of Humanities",department:"Communication",subdiscipline:""},
    {name:"Writing for Media",code:"COM 230",level:"Sophomore",college:"College of Humanities",department:"Communication",subdiscipline:""},
    {name:"Introduction to Criminal Justice",code:"CRJ 101",level:"Freshman",college:"College of Social Sciences",department:"Criminal Justice",subdiscipline:""},
    {name:"Criminology",code:"CRJ 210",level:"Sophomore",college:"College of Social Sciences",department:"Criminal Justice",subdiscipline:""},
    {name:"Policing",code:"CRJ 220",level:"Sophomore",college:"College of Social Sciences",department:"Criminal Justice",subdiscipline:""},
    {name:"Courts & Sentencing",code:"CRJ 230",level:"Sophomore",college:"College of Social Sciences",department:"Criminal Justice",subdiscipline:""},
    {name:"Corrections",code:"CRJ 240",level:"Sophomore",college:"College of Social Sciences",department:"Criminal Justice",subdiscipline:""},
    {name:"Criminal Law",code:"CRJ 250",level:"Sophomore",college:"College of Social Sciences",department:"Criminal Justice",subdiscipline:""},
    {name:"Criminal Procedure",code:"CRJ 260",level:"Sophomore",college:"College of Social Sciences",department:"Criminal Justice",subdiscipline:""},
    {name:"Programming I",code:"CSC 110",level:"Freshman",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Programming II",code:"CSC 120",level:"Freshman",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Data Structures",code:"CSC 210",level:"Sophomore",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Discrete Mathematics",code:"CSC 220",level:"Sophomore",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Computer Systems",code:"CSC 230",level:"Sophomore",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Databases",code:"CSC 240",level:"Sophomore",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Networks",code:"CSC 250",level:"Sophomore",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Software Engineering",code:"CSC 260",level:"Sophomore",college:"College of Computing",department:"Computer Science",subdiscipline:""},
    {name:"Intro to Communication Sciences & Disorders",code:"CSD 101",level:"Freshman",college:"College of Health Sciences",department:"Communication Sciences & Disorders",subdiscipline:""},
    {name:"Speech & Hearing Science with Lab",code:"CSD 210",level:"Sophomore",college:"College of Health Sciences",department:"Communication Sciences & Disorders",subdiscipline:""},
    {name:"Phonetics",code:"CSD 220",level:"Sophomore",college:"College of Health Sciences",department:"Communication Sciences & Disorders",subdiscipline:""},
    {name:"Anatomy & Physiology for Speech",code:"CSD 230",level:"Sophomore",college:"College of Health Sciences",department:"Communication Sciences & Disorders",subdiscipline:""},
    {name:"Language Development",code:"CSD 240",level:"Sophomore",college:"College of Health Sciences",department:"Communication Sciences & Disorders",subdiscipline:""},
    {name:"Audiology Foundations",code:"CSD 250",level:"Sophomore",college:"College of Health Sciences",department:"Communication Sciences & Disorders",subdiscipline:""},
    {name:"Security Foundations",code:"CYB 201",level:"Sophomore",college:"College of Computing",department:"Cybersecurity",subdiscipline:""},
    {name:"Systems Hardening",code:"CYB 210",level:"Sophomore",college:"College of Computing",department:"Cybersecurity",subdiscipline:""},
    {name:"Network Security",code:"CYB 220",level:"Sophomore",college:"College of Computing",department:"Cybersecurity",subdiscipline:""},
    {name:"Scripting for Security",code:"CYB 230",level:"Sophomore",college:"College of Computing",department:"Cybersecurity",subdiscipline:""},
    {name:"Data Science Foundations",code:"DAS 201",level:"Sophomore",college:"College of Computing",department:"Data Science",subdiscipline:""},
    {name:"Circuits II with Lab",code:"ECE 201",level:"Sophomore",college:"College of Engineering",department:"Electrical Engineering",subdiscipline:""},
    {name:"Digital Logic Design",code:"ECE 210",level:"Sophomore",college:"College of Engineering",department:"Electrical Engineering",subdiscipline:""},
    {name:"Electronics I with Lab",code:"ECE 220",level:"Sophomore",college:"College of Engineering",department:"Electrical Engineering",subdiscipline:""},
    {name:"Signals & Systems",code:"ECE 230",level:"Sophomore",college:"College of Engineering",department:"Electrical Engineering",subdiscipline:""},
    {name:"Electromagnetics",code:"ECE 240",level:"Sophomore",college:"College of Engineering",department:"Electrical Engineering",subdiscipline:""},
    {name:"Microcontrollers & Embedded Systems with Lab",code:"ECE 250",level:"Sophomore",college:"College of Engineering",department:"Electrical Engineering",subdiscipline:""},
    {name:"Microeconomics",code:"ECO 201",level:"Sophomore",college:"College of Business",department:"Economics",subdiscipline:""},
    {name:"Macroeconomics",code:"ECO 202",level:"Sophomore",college:"College of Business",department:"Economics",subdiscipline:""},
    {name:"Foundations of Education",code:"EDU 101",level:"Freshman",college:"College of Education",department:"Education",subdiscipline:""},
    {name:"Human Development & Learning",code:"EDU 210",level:"Sophomore",college:"College of Education",department:"Education",subdiscipline:""},
    {name:"Learning Sciences & Motivation",code:"EDU 220",level:"Sophomore",college:"College of Education",department:"Education",subdiscipline:""},
    {name:"Diversity Equity & Inclusion in Education",code:"EDU 230",level:"Sophomore",college:"College of Education",department:"Education",subdiscipline:""},
    {name:"Assessment & Data in Education",code:"EDU 240",level:"Sophomore",college:"College of Education",department:"Education",subdiscipline:""},
    {name:"Learning Environments & Behavior Intervention",code:"EDU 250",level:"Sophomore",college:"College of Education",department:"Education",subdiscipline:""},
    {name:"English Composition I",code:"ENG 101",level:"Freshman",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"English Composition II: Research & Argument",code:"ENG 102",level:"Freshman",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"Introduction to Literary Studies",code:"ENG 201",level:"Sophomore",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"Literary Analysis & Interpretation",code:"ENG 210",level:"Sophomore",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"World Literature",code:"ENG 220",level:"Sophomore",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"British Literature I",code:"ENG 230",level:"Sophomore",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"British Literature II",code:"ENG 231",level:"Sophomore",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"American Literature I",code:"ENG 240",level:"Sophomore",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"American Literature II",code:"ENG 241",level:"Sophomore",college:"College of Humanities",department:"English",subdiscipline:""},
    {name:"Entrepreneurship in Creative Industries",code:"ENT 210",level:"Sophomore",college:"College of Business",department:"Management",subdiscipline:"Entrepreneurship"},
    {name:"Foundations of Environmental Science with Lab",code:"ENV 101",level:"Freshman",college:"College of the Environment",department:"Environmental Science",subdiscipline:""},
    {name:"Environmental Data Analysis with Lab",code:"ENV 201",level:"Sophomore",college:"College of the Environment",department:"Environmental Science",subdiscipline:""},
    {name:"Ecology & Ecosystems with Lab",code:"ENV 202",level:"Sophomore",college:"College of the Environment",department:"Environmental Science",subdiscipline:""},
    {name:"Earth Systems with Lab",code:"EPS 101",level:"Freshman",college:"College of the Environment",department:"Earth & Planetary Sciences",subdiscipline:""},
    {name:"Earth Materials & Minerals with Lab",code:"EPS 110",level:"Freshman",college:"College of the Environment",department:"Earth & Planetary Sciences",subdiscipline:""},
    {name:"Earth Surface Processes with Lab",code:"EPS 120",level:"Freshman",college:"College of the Environment",department:"Earth & Planetary Sciences",subdiscipline:""},
    {name:"Earth History & Paleoenvironments with Lab",code:"EPS 210",level:"Sophomore",college:"College of the Environment",department:"Earth & Planetary Sciences",subdiscipline:""},
    {name:"Introduction to Film & Media Studies",code:"FMS 101",level:"Freshman",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Film History I",code:"FMS 110",level:"Freshman",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Film History II",code:"FMS 111",level:"Freshman",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Media Industries & Institutions",code:"FMS 120",level:"Freshman",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Film & Media Analysis",code:"FMS 130",level:"Freshman",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Screenwriting I",code:"FMS 201",level:"Sophomore",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Media Research Methods",code:"FMS 210",level:"Sophomore",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Writing for Film & Media",code:"FMS 220",level:"Sophomore",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Media Production I",code:"FMS 230",level:"Sophomore",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Media Production II",code:"FMS 231",level:"Sophomore",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Sound Editing & Post-Production",code:"FMS 240",level:"Sophomore",college:"College of the Arts",department:"Film & Media Studies",subdiscipline:""},
    {name:"Introduction to Geography",code:"GEO 101",level:"Freshman",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"Global Systems & Cultures",code:"GEO 120",level:"Freshman",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"Physical Geography",code:"GEO 130",level:"Freshman",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"Human Geography",code:"GEO 140",level:"Freshman",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"Cartography & GIS I",code:"GEO 210",level:"Sophomore",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"Spatial Data Analysis",code:"GEO 220",level:"Sophomore",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"Remote Sensing",code:"GEO 230",level:"Sophomore",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"Environmental Geography",code:"GEO 240",level:"Sophomore",college:"College of Humanities",department:"Geography",subdiscipline:""},
    {name:"GIS I: Mapping & Data with Lab",code:"GSS 210",level:"Sophomore",college:"College of the Environment",department:"Earth & Planetary Sciences",subdiscipline:"Geospatial Science"},
    {name:"Remote Sensing & Cartography with Lab",code:"GSS 220",level:"Sophomore",college:"College of the Environment",department:"Earth & Planetary Sciences",subdiscipline:"Geospatial Science"},
    {name:"Introduction to Gender & Sexuality Studies",code:"GSX 101",level:"Freshman",college:"College of Social Sciences",department:"Gender & Sexuality Studies",subdiscipline:""},
    {name:"Gender in Society",code:"GSX 210",level:"Sophomore",college:"College of Social Sciences",department:"Gender & Sexuality Studies",subdiscipline:""},
    {name:"Sexuality & Culture",code:"GSX 220",level:"Sophomore",college:"College of Social Sciences",department:"Gender & Sexuality Studies",subdiscipline:""},
    {name:"Global Gender Issues",code:"GSX 240",level:"Sophomore",college:"College of Social Sciences",department:"Gender & Sexuality Studies",subdiscipline:""},
    {name:"Healthcare Administration & Operations",code:"HCA 210",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:"Healthcare Administration"},
    {name:"Healthcare Finance",code:"HCA 220",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:"Healthcare Administration"},
    {name:"Health Informatics Foundations",code:"HIN 210",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:"Health Informatics"},
    {name:"Healthcare Data Standards & Interoperability",code:"HIN 220",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:"Health Informatics"},
    {name:"Historical Thinking & Methods",code:"HIS 201",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"World History I",code:"HIS 210",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"World History II",code:"HIS 211",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"U.S. History I",code:"HIS 220",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"U.S. History II",code:"HIS 221",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"Modern Europe",code:"HIS 230",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"History of Asia",code:"HIS 240",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"History of the Americas",code:"HIS 250",level:"Sophomore",college:"College of Humanities",department:"History",subdiscipline:""},
    {name:"IS Foundations & Business Processes",code:"INF 201",level:"Sophomore",college:"College of Computing",department:"Information Technology",subdiscipline:""},
    {name:"Business Programming",code:"INF 210",level:"Sophomore",college:"College of Computing",department:"Information Technology",subdiscipline:""},
    {name:"Systems & Data Concepts",code:"INF 215",level:"Sophomore",college:"College of Computing",department:"Information Technology",subdiscipline:""},
    {name:"IT Service Management",code:"INF 220",level:"Sophomore",college:"College of Computing",department:"Information Technology",subdiscipline:""},
    {name:"Work Design & Ergonomics",code:"ISE 210",level:"Sophomore",college:"College of Engineering",department:"Industrial & Systems Engineering",subdiscipline:""},
    {name:"Operations Research I",code:"ISE 220",level:"Sophomore",college:"College of Engineering",department:"Industrial & Systems Engineering",subdiscipline:""},
    {name:"Operations Research II",code:"ISE 230",level:"Sophomore",college:"College of Engineering",department:"Industrial & Systems Engineering",subdiscipline:""},
    {name:"Simulation Modeling",code:"ISE 240",level:"Sophomore",college:"College of Engineering",department:"Industrial & Systems Engineering",subdiscipline:""},
    {name:"Quality Engineering",code:"ISE 250",level:"Sophomore",college:"College of Engineering",department:"Industrial & Systems Engineering",subdiscipline:""},
    {name:"Smart Manufacturing & Industry 4.0",code:"ISE 260",level:"Sophomore",college:"College of Engineering",department:"Industrial & Systems Engineering",subdiscipline:""},
    {name:"Legal Systems & Reasoning",code:"LGS 201",level:"Sophomore",college:"College of Business",department:"Legal Studies",subdiscipline:""},
    {name:"Legal Research & Writing I",code:"LGS 210",level:"Sophomore",college:"College of Business",department:"Legal Studies",subdiscipline:""},
    {name:"Civil Litigation",code:"LGS 220",level:"Sophomore",college:"College of Business",department:"Legal Studies",subdiscipline:""},
    {name:"Contracts",code:"LGS 230",level:"Sophomore",college:"College of Business",department:"Legal Studies",subdiscipline:""},
    {name:"Torts",code:"LGS 240",level:"Sophomore",college:"College of Business",department:"Legal Studies",subdiscipline:""},
    {name:"Constitutional Law",code:"LGS 250",level:"Sophomore",college:"College of Business",department:"Legal Studies",subdiscipline:""},
    {name:"College Algebra",code:"MAT 115",level:"Freshman",college:"College of Science",department:"Mathematics",subdiscipline:""},
    {name:"Calculus I",code:"MAT 171",level:"Freshman",college:"College of Science",department:"Mathematics",subdiscipline:""},
    {name:"Calculus II",code:"MAT 172",level:"Freshman",college:"College of Science",department:"Mathematics",subdiscipline:""},
    {name:"Linear Algebra",code:"MAT 251",level:"Sophomore",college:"College of Science",department:"Mathematics",subdiscipline:""},
    {name:"Differential Equations (Math Major)",code:"MAT 252",level:"Sophomore",college:"College of Science",department:"Mathematics",subdiscipline:""},
    {name:"Calculus III",code:"MAT 273",level:"Sophomore",college:"College of Science",department:"Mathematics",subdiscipline:""},
    {name:"Differential Equations (Math Major II)",code:"MAT 280",level:"Sophomore",college:"College of Science",department:"Mathematics",subdiscipline:""},
    {name:"Thermodynamics I",code:"MEE 210",level:"Sophomore",college:"College of Engineering",department:"Mechanical Engineering",subdiscipline:""},
    {name:"Heat Transfer",code:"MEE 230",level:"Sophomore",college:"College of Engineering",department:"Mechanical Engineering",subdiscipline:""},
    {name:"Manufacturing Processes",code:"MEE 240",level:"Sophomore",college:"College of Engineering",department:"Mechanical Engineering",subdiscipline:""},
    {name:"Mechanical Design I",code:"MEE 250",level:"Sophomore",college:"College of Engineering",department:"Mechanical Engineering",subdiscipline:""},
    {name:"Survey of the Music Industry",code:"MUS 101",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Survey of the Music Industry (Tech)",code:"MUS 105",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Music Theory for Producers & Managers",code:"MUS 110",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Audio Production I",code:"MUS 120",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Audio Production II",code:"MUS 121",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Music Business Communication",code:"MUS 130",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"DAW Editing & Workflow",code:"MUS 140",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"MIDI Synthesis & Sampling",code:"MUS 150",level:"Freshman",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Tour Management & Logistics",code:"MUS 210",level:"Sophomore",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Studio Recording Techniques",code:"MUS 221",level:"Sophomore",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Copyright & Music Law",code:"MUS 225",level:"Sophomore",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Artist Management",code:"MUS 230",level:"Sophomore",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Sound Design",code:"MUS 235",level:"Sophomore",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Acoustics & Psychoacoustics",code:"MUS 240",level:"Sophomore",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Audio Hardware Signal Flow & Troubleshooting",code:"MUS 250",level:"Sophomore",college:"College of the Arts",department:"Music",subdiscipline:""},
    {name:"Foundations of Nutrition with Lab",code:"NTR 101",level:"Freshman",college:"College of Health Sciences",department:"Nutrition",subdiscipline:""},
    {name:"Human Nutrition & Metabolism",code:"NTR 201",level:"Sophomore",college:"College of Health Sciences",department:"Nutrition",subdiscipline:""},
    {name:"Functional Foods & Ingredient Chemistry with Lab",code:"NTR 210",level:"Sophomore",college:"College of Health Sciences",department:"Nutrition",subdiscipline:""},
    {name:"Nutrition Across the Lifespan",code:"NTR 220",level:"Sophomore",college:"College of Health Sciences",department:"Nutrition",subdiscipline:""},
    {name:"Org Leadership Foundations",code:"ORL 201",level:"Sophomore",college:"College of Business",department:"Management",subdiscipline:"Organizational Leadership"},
    {name:"Teams & Conflict",code:"ORL 241",level:"Sophomore",college:"College of Business",department:"Management",subdiscipline:"Organizational Leadership"},
    {name:"Introduction to Philosophy",code:"PHI 101",level:"Freshman",college:"College of Humanities",department:"Philosophy",subdiscipline:""},
    {name:"Ethics",code:"PHI 120",level:"Freshman",college:"College of Humanities",department:"Philosophy",subdiscipline:""},
    {name:"Logic & Critical Thinking",code:"PHI 210",level:"Sophomore",college:"College of Humanities",department:"Philosophy",subdiscipline:""},
    {name:"Ancient Philosophy",code:"PHI 220",level:"Sophomore",college:"College of Humanities",department:"Philosophy",subdiscipline:""},
    {name:"Modern Philosophy",code:"PHI 230",level:"Sophomore",college:"College of Humanities",department:"Philosophy",subdiscipline:""},
    {name:"Philosophy of Mind",code:"PHI 240",level:"Sophomore",college:"College of Humanities",department:"Philosophy",subdiscipline:""},
    {name:"Physics for Life Sciences with Lab",code:"PHY 101",level:"Freshman",college:"College of Science",department:"Physics",subdiscipline:""},
    {name:"University Physics I with Lab",code:"PHY 201",level:"Sophomore",college:"College of Science",department:"Physics",subdiscipline:""},
    {name:"University Physics II with Lab",code:"PHY 202",level:"Sophomore",college:"College of Science",department:"Physics",subdiscipline:""},
    {name:"Foundations of Public Administration",code:"PLP 201",level:"Sophomore",college:"College of Business",department:"Public Administration",subdiscipline:""},
    {name:"Public Policy Analysis",code:"PLP 210",level:"Sophomore",college:"College of Business",department:"Public Administration",subdiscipline:""},
    {name:"Public Budgeting & Finance",code:"PLP 220",level:"Sophomore",college:"College of Business",department:"Public Administration",subdiscipline:""},
    {name:"Administrative Law & Governance",code:"PLP 230",level:"Sophomore",college:"College of Business",department:"Public Administration",subdiscipline:""},
    {name:"Program Evaluation",code:"PLP 240",level:"Sophomore",college:"College of Business",department:"Public Administration",subdiscipline:""},
    {name:"Ethics in Public Service",code:"PLP 250",level:"Sophomore",college:"College of Business",department:"Public Administration",subdiscipline:""},
    {name:"American Government",code:"POL 101",level:"Freshman",college:"College of Social Sciences",department:"Political Science",subdiscipline:""},
    {name:"Political Theory",code:"POL 210",level:"Sophomore",college:"College of Social Sciences",department:"Political Science",subdiscipline:""},
    {name:"Comparative Politics",code:"POL 220",level:"Sophomore",college:"College of Social Sciences",department:"Political Science",subdiscipline:""},
    {name:"Global Security & Geopolitics",code:"POL 230",level:"Sophomore",college:"College of Social Sciences",department:"Political Science",subdiscipline:""},
    {name:"Research Methods in Political Science",code:"POL 240",level:"Sophomore",college:"College of Social Sciences",department:"Political Science",subdiscipline:""},
    {name:"Intro Psychology",code:"PSY 101",level:"Freshman",college:"College of Social Sciences",department:"Psychology",subdiscipline:""},
    {name:"Lifespan Development",code:"PSY 210",level:"Sophomore",college:"College of Social Sciences",department:"Psychology",subdiscipline:""},
    {name:"Social Psychology",code:"PSY 220",level:"Sophomore",college:"College of Social Sciences",department:"Psychology",subdiscipline:""},
    {name:"Cognitive Psychology",code:"PSY 230",level:"Sophomore",college:"College of Social Sciences",department:"Psychology",subdiscipline:""},
    {name:"Abnormal Psychology",code:"PSY 240",level:"Sophomore",college:"College of Social Sciences",department:"Psychology",subdiscipline:""},
    {name:"Foundations of Public Health",code:"PUH 101",level:"Freshman",college:"College of Health Sciences",department:"Public Health",subdiscipline:""},
    {name:"Epidemiology I",code:"PUH 210",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:""},
    {name:"Biostatistics for Public Health",code:"PUH 220",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:""},
    {name:"Environmental & Occupational Health",code:"PUH 230",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:""},
    {name:"Health Policy & Systems",code:"PUH 240",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:""},
    {name:"Social & Behavioral Determinants of Health",code:"PUH 250",level:"Sophomore",college:"College of Health Sciences",department:"Public Health",subdiscipline:""},
    {name:"Introduction to Religious Studies",code:"REL 101",level:"Freshman",college:"College of Humanities",department:"Religious Studies",subdiscipline:""},
    {name:"Comparative Religion",code:"REL 210",level:"Sophomore",college:"College of Humanities",department:"Religious Studies",subdiscipline:""},
    {name:"Sacred Texts: Methods & Interpretation",code:"REL 220",level:"Sophomore",college:"College of Humanities",department:"Religious Studies",subdiscipline:""},
    {name:"Religion in America",code:"REL 230",level:"Sophomore",college:"College of Humanities",department:"Religious Studies",subdiscipline:""},
    {name:"Religion & Politics",code:"REL 240",level:"Sophomore",college:"College of Humanities",department:"Religious Studies",subdiscipline:""},
    {name:"Religion Ethics & Society",code:"REL 250",level:"Sophomore",college:"College of Humanities",department:"Religious Studies",subdiscipline:""},
    {name:"Introduction to Sociology",code:"SOC 101",level:"Freshman",college:"College of Social Sciences",department:"Sociology",subdiscipline:""},
    {name:"Social Problems",code:"SOC 210",level:"Sophomore",college:"College of Social Sciences",department:"Sociology",subdiscipline:""},
    {name:"Social Inequality",code:"SOC 220",level:"Sophomore",college:"College of Social Sciences",department:"Sociology",subdiscipline:""},
    {name:"Introduction to Statistics",code:"STA 201",level:"Sophomore",college:"College of Science",department:"Statistics",subdiscipline:""},
    {name:"Information Literacy & Research",code:"UNI 110",level:"Freshman",college:"Aloha University",department:"University Core",subdiscipline:""},
    {name:"Data & AI Literacy",code:"UNI 120",level:"Freshman",college:"Aloha University",department:"University Core",subdiscipline:""},
    {name:"Drawing I",code:"VIS 101",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Design Foundations: 2D",code:"VIS 110",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"3D Modeling & Spatial Design",code:"VIS 120",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Digital Design Foundations",code:"VIS 130",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Color Theory",code:"VIS 140",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Typography I",code:"VIS 150",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"History of Design",code:"VIS 160",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Photography for Designers",code:"VIS 170",level:"Freshman",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Graphic Design Studio I",code:"VIS 201",level:"Sophomore",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Graphic Design Studio II",code:"VIS 202",level:"Sophomore",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"UX Foundations",code:"VIS 210",level:"Sophomore",college:"College of the Arts",department:"Visual Arts",subdiscipline:""},
    {name:"Digital Content Creation",code:"VIS 220",level:"Sophomore",college:"College of the Arts",department:"Visual Arts",subdiscipline:""}
];
